#
# Globo OpenDayLight Controller base docker image
# Check it at https://hub.docker.com/r/globocom/odl/
#

FROM opendaylight/odl:4.4.0

WORKDIR /opt/opendaylight

EXPOSE 8181
EXPOSE 8101
EXPOSE 6633
EXPOSE 6653
