#!/bin/bash

LOGFILE='/tmp/gerador_vips.log';

#Verifica arquivo de log
if [ -f $LOGFILE ]; then
        if [ ! -w $LOGFILE ]; then
                echo "ERRO: Arquivo de log $LOGFILE sem permissoes de escrita."
                exit 1
        fi
else
        touch $LOGFILE
        chmod 666 $LOGFILE
fi
echo "$(date): ${*}" >> $LOGFILE

echo "$(date): Script start" >> $LOGFILE
echo "sleep 7..." >> $LOGFILE
sleep 1
echo "sleep 6..." >> $LOGFILE
sleep 1
echo "sleep 5..." >> $LOGFILE
sleep 1
echo "sleep 4..." >> $LOGFILE
sleep 1
echo "sleep 3..." >> $LOGFILE
sleep 1
echo "sleep 2..." >> $LOGFILE
sleep 1
echo "sleep 1..." >> $LOGFILE
sleep 1

echo "$(date): Done" >> $LOGFILE
#simulate check status of vip server pool member
#echo 3
#Simulate pool check_status  Script
#echo '{"7619":{"15922":3,"15921":7}}'

#exit status 0 OK !=0 error
exit 0
