#!/bin/bash

echo 3
#echo $"Parametros: $0 $1 $2 $3 $4 $5 $6 $7" >&2
#Simula Script para verificar status pool members
#echo '{"server_pool_id": 3, "server_pool_members": [{"id": 6 , "status": 0}, {"id": 5, "status": 0}]}'
exit 0
