#!/bin/bash

LOGFILE='/tmp/gerador_vips.log';

#Verifica arquivo de log
if [ -f $LOGFILE ]; then
        if [ ! -w $LOGFILE ]; then
                echo "ERRO: Arquivo de log $LOGFILE sem permissoes de escrita."
                exit 1
        fi
else
        touch $LOGFILE
        chmod 666 $LOGFILE
fi
echo "$(date): ${*}" >> $LOGFILE

echo "$(date): Ta rodando" >> $LOGFILE

sleep 5 

echo "$(date): Rodou" >> $LOGFILE
echo 3
#echo $"Parametros: $0 $1 $2 $3 $4 $5 $6 $7" >&2
#Simula Script para verificar status pool members
#echo '{"server_pool_id": 3, "server_pool_members": [{"id": 6 , "status": 0}, {"id": 5, "status": 0}]}'
exit 1
