#!/bin/bash

# navlan -A ambiente(id_ambiente) -N vlans(nome) -R vlans(rede_oct1.rede_oct2.rede_oct3.red_oct4/bloco) -I vlans(num_vlan) --equip <NOME1,NOME2,etc> --cria

echo $"Parametros: $0 $1 $2 $3 $4 $5 $6 $7 $8 $9 ${10} ${11}" >&2
echo "Teste"
exit 0
